<div className="w-[1920px] h-[4394px] relative bg-white">
    <div className="w-[1920px] h-[198px] left-0 top-[830px] absolute bg-white" />
    <div className="w-[33px] h-[21px] left-[1868px] top-[132px] absolute">
        <div className="w-[32.42px] h-[0px] left-0 top-[4px] absolute border-4 border-black"></div>
        <div className="w-[32.42px] h-[0px] left-0 top-[12.25px] absolute border-4 border-black"></div>
        <div className="w-[32.42px] h-[0px] left-0 top-[20.50px] absolute border-4 border-black"></div>
    </div>
    <div className="w-[721px] left-[522px] top-[4346.24px] absolute">
        <div className="w-[82px] h-[19.79px] left-[639px] top-[7.42px] absolute text-black text-xl font-bold font-['Calibri']">Employee</div>
        <div className="w-[150px] h-[34.98px] left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Simple Grids 2023</div>
        <div className="w-[126px] h-[34.98px] left-[250px] top-0 absolute text-black text-xl font-bold font-['Calibri']">Privacy & Legal</div>
        <div className="w-[63px] h-[34.98px] left-[476px] top-0 absolute text-black text-xl font-bold font-['Calibri']">Careers</div>
    </div>
    <div className="w-[1838.05px] h-[209px] left-[32px] top-[3546px] absolute">
        <div className="left-0 top-0 absolute text-black text-6xl font-bold font-['Calibri']">Trusted by</div>
        <div className="w-[1764.05px] h-[100px] left-[74px] top-[109px] absolute justify-start items-start gap-6 inline-flex">
            <img className="w-[208.96px] h-[100px]" src="https://via.placeholder.com/209x100" />
            <img className="w-[78.62px] h-[100px]" src="https://via.placeholder.com/79x100" />
            <img className="w-[470.89px] h-[100px]" src="https://via.placeholder.com/471x100" />
            <img className="w-[351.17px] h-[100px]" src="https://via.placeholder.com/351x100" />
            <img className="w-[236.57px] h-[100px]" src="https://via.placeholder.com/237x100" />
            <img className="w-[297.85px] h-[100px]" src="https://via.placeholder.com/298x100" />
        </div>
    </div>
    <div className="w-[1920px] h-[404px] left-0 top-[3865px] absolute">
        <div className="w-[1920px] h-[404px] left-0 top-0 absolute bg-white" />
        <div className="w-[1740px] h-[300px] left-[72px] top-[41px] absolute">
            <div className="left-0 top-[1px] absolute text-black text-6xl font-bold font-['Calibri']">Join as a Service Provider</div>
            <div className="w-[1194px] h-[251px] left-[1px] top-[49px] absolute text-black text-[25px] font-normal font-['Calibri']">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
            <img className="w-[484px] h-[235px] left-[1256px] top-0 absolute" src="https://via.placeholder.com/484x235" />
        </div>
        <div className="w-[319.95px] h-[75.57px] left-[1462px] top-[304px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[25.37px] top-[25px] absolute text-white text-xl font-normal font-['Calibri']">Join as a service provider</div>
        </div>
    </div>
    <div className="w-[1920px] h-[810px] left-0 top-[1852px] absolute">
        <div className="w-[1920px] h-[810px] left-0 top-0 absolute bg-white shadow" />
        <div className="w-[1920px] h-[347px] pl-[22px] pt-[46px] pb-[43px] left-0 top-[50px] absolute justify-end items-start gap-[50px] inline-flex">
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Assessment - Retrofit</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Assessment - EPC</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Thermal Imaging</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">EICR</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Solar Panel Cleaning</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
        </div>
        <div className="w-[1920px] h-[347px] pl-[22px] pt-[46px] pb-[43px] left-0 top-[350px] absolute justify-end items-start gap-[50px] inline-flex">
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Heat Pump Quality Audit</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Retrofit Co-ordination</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Heat Pump Maintenance</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">Heat Loss Survey</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
            <div className="w-[409px] h-[258px] relative">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[18px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">EV charger installation</div>
                <div className="left-[345px] top-[220px] absolute text-center text-black text-xl font-bold font-['Calibri']">£240</div>
                <div className="w-[110px] h-52 left-[299px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
            </div>
        </div>
        <div className="left-[27px] top-[34px] absolute text-black text-[40px] font-bold font-['Calibri']">All Services</div>
    </div>
    <div className="w-[1920px] h-[284px] left-0 top-[674px] absolute">
        <div className="w-[1920px] h-[284px] left-0 top-0 absolute">
            <div className="w-[1920px] h-[284px] left-0 top-0 absolute bg-zinc-300" />
            <div className="left-[431px] top-[52px] absolute text-center text-black text-6xl font-bold font-['Calibri']">Find the perfect package or service for you </div>
        </div>
        <div className="w-[139px] h-[72px] left-[91px] top-[145px] absolute">
            <div className="w-[139px] h-[50px] left-0 top-[11px] absolute bg-white rounded-[20px] shadow" />
            <div className="left-[23px] top-[21px] absolute text-black text-[25px] font-normal font-['Calibri']">Postcode</div>
        </div>
        <div className="w-[556px] h-[45px] left-[253px] top-[158.50px] absolute">
        </div>
        <div className="w-[185px] h-[47px] left-[832px] top-[157.50px] absolute">
            <div className="w-[185px] h-[47px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[11px] absolute text-white text-xl font-normal font-['Calibri']">Age</div>
        </div>
        <div className="w-80 h-12 left-[1040px] top-[157px] absolute">
            <div className="w-80 h-12 left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[11px] absolute text-white text-xl font-normal font-['Calibri']">Problems to address</div>
        </div>
        <div className="w-72 h-[92px] left-[1383px] top-[156px] absolute">
            <div className="w-72 h-[92px] left-0 top-0 absolute bg-white rounded-[20px]" />
            <div className="w-[186px] left-[27px] top-[10px] absolute opacity-30 text-black text-xl font-normal font-['Calibri']">Narrate the problem in your own words/ click to speak</div>
            <div className="w-10 h-10 left-[228px] top-[26px] absolute rounded-[10px] border border-green-700" />
        </div>
        <div className="w-[142px] h-[47px] left-[1694px] top-[157.50px] absolute">
            <div className="w-[142px] h-[47px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[14px] top-[11px] absolute text-white text-xl font-normal font-['Calibri']">See Results</div>
        </div>
    </div>
    <div className="w-[1920px] h-[754.28px] left-0 top-[2679.72px] absolute">
        <div className="w-[1920px] h-[715px] left-0 top-[39.28px] absolute bg-white shadow" />
        <div className="w-[319.95px] h-[75.57px] left-[1139.84px] top-[150.28px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[29.72px] absolute text-white text-xl font-normal font-['Calibri']">Number of Bedrooms</div>
        </div>
        <div className="w-[319.95px] h-[75.57px] left-[1462px] top-[630.28px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[25.37px] top-[25px] absolute text-white text-xl font-normal font-['Calibri']">Request a quote</div>
        </div>
        <div className="w-80 h-[75.57px] left-[799.89px] top-[150.28px] absolute">
            <div className="w-80 h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-80 h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[115.02px] left-[35.43px] top-[29.72px] absolute text-white text-xl font-normal font-['Calibri']">Property Type</div>
        </div>
        <div className="w-[319.95px] h-[75.57px] left-[459.95px] top-[150.28px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[29.72px] absolute text-white text-xl font-normal font-['Calibri']">Solutions</div>
        </div>
        <div className="w-[319.95px] h-[75.57px] left-[120px] top-[150.28px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[29.72px] absolute text-white text-xl font-normal font-['Calibri']">Service Types</div>
        </div>
        <div className="w-[319.95px] h-[75.57px] left-[1478px] top-[150.28px] absolute">
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="w-[319.95px] h-[75.57px] left-0 top-0 absolute bg-green-700 rounded-2xl" />
            <div className="left-[35.37px] top-[29.72px] absolute text-white text-xl font-normal font-['Calibri']">Property Age</div>
        </div>
        <div className="left-[1515.16px] top-0 absolute text-white text-xl font-normal font-['Calibri']">Max Number of rooms</div>
        <div className="left-[27px] top-[73.28px] absolute text-black text-[40px] font-bold font-['Calibri']">Request a quote</div>
        <div className="w-[1621px] h-[65px] left-[144px] top-[332.28px] absolute text-black text-xl font-normal font-['Calibri']">Hi there, I am looking for an insulation upgrade along with a Heat pump installation to convert my old oil boiler on my period property located near Oxford. I would like to have someone check out my property </div>
    </div>
    <div className="w-[1262.55px] h-[434px] left-[314px] top-[214px] absolute">
        <div className="w-[1262.55px] h-[434px] left-0 top-0 absolute bg-white" />
        <div className="w-[1168.13px] h-[416.34px] left-[47.35px] top-[13.81px] absolute">
            <div className="w-[1167.85px] h-[159.13px] left-0 top-0 absolute">
                <div className="w-[215.68px] h-[38.34px] left-[-0px] top-[0.53px] absolute text-center text-black text-[39.45px] font-bold font-['Calibri']">How it works</div>
                <div className="w-[757.53px] left-[4.60px] top-[40.77px] absolute text-black text-base font-normal font-['Calibri']">We vet a variety of service providers, ensuring that they are all certified and qualified to perform each service they offer and meet all government standards and more. This gives you peace of mind, as you can now be sure that the data you’re receiving is from a trustworthy, professional source, with no pressure on you to make any further purchases. We also have Verified Partners who </div>
                <div className="w-[387.31px] h-[159.13px] left-[780.54px] top-0 absolute bg-zinc-300" />
            </div>
            <div className="w-[1167.48px] h-[251.29px] left-[0.66px] top-[165.05px] absolute">
                <div className="left-[809.48px] top-[-0px] absolute text-right text-black text-[39.45px] font-bold font-['Calibri']">What are the benefits</div>
                <div className="w-[521.46px] left-[432.68px] top-[51.29px] absolute"><span style="text-black text-base font-bold font-['Calibri']">Reduce your Energy Bills<br/>Reduce your Carbon Emission<br/>Increase your comfort<br/></span><span style="text-black text-base font-normal font-['Calibri']"><br/>Are rooms in your house too hot or cold?<br/>Are you experiencing draughty windows?<br/>Are you thinking of adding a heat pump?<br/>Are you looking for Solar Panel installation?<br/>Are you planning to sell your house soon and would like to increase it’s value?<br/>Are you buying an Electric Vehicle?</span></div>
                <div className="w-[223.58px] left-[940.33px] top-[51.29px] absolute text-right text-black text-base font-bold font-['Calibri']">Ordering a Whole House energy Health Check-up package from us will allow you to get all the information you need to make an informed decision about your property to combat these problems and more!</div>
                <div className="w-[387.31px] h-[231.47px] left-0 top-[13.15px] absolute bg-zinc-300" />
            </div>
        </div>
    </div>
    <div className="w-[1920px] h-[871px] left-0 top-[981px] absolute">
        <div className="w-[1920px] h-[871px] left-0 top-0 absolute bg-white shadow" />
        <div className="w-[398px] h-[94px] left-[761px] top-[733px] absolute">
            <div className="w-[398px] h-[94px] left-0 top-0 absolute bg-green-700 rounded-[20px]" />
            <div className="left-[114px] top-[19px] absolute text-white text-[25px] font-normal font-['Calibri']">See more results </div>
        </div>
        <div className="w-[1920px] h-[347px] left-0 top-[50px] absolute">
            <div className="w-[409px] h-[258px] left-[940px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Enhance</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £600</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[481px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Solar PV + Battery Charger</div>
                <div className="left-[272px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']"> From £28,000</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="left-[217px] top-[17px] absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                <div className="w-[141px] h-[105px] left-[217px] top-[51px] absolute flex-col justify-start items-start gap-[3px] inline-flex">
                    <div className="text-black text-xl font-normal font-['Calibri']">Solar PV - 4kW</div>
                    <div className="text-black text-xl font-normal font-['Calibri']">Battery - 10KWH </div>
                    <div className="text-black text-xl font-normal font-['Calibri']">DNO applications</div>
                    <div className="text-black text-xl font-normal font-['Calibri']">Bird proofing</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1399px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1488</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1869px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[340px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">£1488</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[22px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Base</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £450</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[166px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="w-[181px] h-[132px] left-0 top-[34px] absolute flex-col justify-center items-start gap-[3px] inline-flex">
                        <div className="text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Return on Investment</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Quotes</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Implementation Plan</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="w-[1920px] h-[347px] left-0 top-[359px] absolute">
            <div className="w-[409px] h-[258px] left-[940px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Champion</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1275</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[481px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Solar PV</div>
                <div className="left-[277px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £20,000</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1399px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1488</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1869px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[340px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">£1488</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[22px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Green</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £985</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
        </div>
        <div className="left-[27px] top-[34px] absolute text-black text-[40px] font-bold font-['Calibri']">All Packages</div>
    </div>
    <div className="w-[1920px] h-[871px] left-0 top-[981px] absolute">
        <div className="w-[1920px] h-[871px] left-0 top-0 absolute bg-white shadow" />
        <div className="w-[1920px] h-[347px] left-0 top-[50px] absolute">
            <div className="w-[409px] h-[258px] left-[940px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Enhance</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £600</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[481px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Solar PV + Battery Charger</div>
                <div className="left-[272px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']"> From £28,000</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="left-[217px] top-[17px] absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                <div className="w-[141px] h-[105px] left-[217px] top-[51px] absolute flex-col justify-start items-start gap-[3px] inline-flex">
                    <div className="text-black text-xl font-normal font-['Calibri']">Solar PV - 4kW</div>
                    <div className="text-black text-xl font-normal font-['Calibri']">Battery - 10KWH </div>
                    <div className="text-black text-xl font-normal font-['Calibri']">DNO applications</div>
                    <div className="text-black text-xl font-normal font-['Calibri']">Bird proofing</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1399px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1488</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1869px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[340px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">£1488</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[22px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Base</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £450</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[166px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="w-[181px] h-[132px] left-0 top-[34px] absolute flex-col justify-center items-start gap-[3px] inline-flex">
                        <div className="text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Return on Investment</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Quotes</div>
                        <div className="text-black text-xl font-normal font-['Calibri']">Implementation Plan</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="w-[1920px] h-[347px] left-0 top-[359px] absolute">
            <div className="w-[409px] h-[258px] left-[940px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Champion</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1275</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[481px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Solar PV</div>
                <div className="left-[277px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £20,000</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1399px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="left-[8px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[292px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £1488</div>
                <div className="left-[8px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">Installation Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[1869px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">[Name of Package]</div>
                <div className="left-[340px] top-[220px] absolute text-black text-xl font-bold font-['Calibri']">£1488</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
            <div className="w-[409px] h-[258px] left-[22px] top-[45px] absolute">
                <img className="w-[409px] h-[258px] left-0 top-0 absolute rounded-[5px] border border-black" src="https://via.placeholder.com/409x258" />
                <div className="w-[409px] h-[51px] left-0 top-[207px] absolute bg-white rounded-bl-[5px] rounded-br-[5px] border border-black" />
                <div className="w-[49px] h-[49px] left-[4px] top-[208px] absolute">
                    <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                    <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                        <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                        <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    </div>
                    <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                        <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                        <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                    </div>
                    <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                        <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                        <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    </div>
                    <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                        <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                        <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                    </div>
                    <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                        <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                    </div>
                </div>
                <div className="left-[58px] top-[210px] absolute text-black text-xl font-bold font-['Calibri']">Energy Green</div>
                <div className="left-[302px] top-[220px] absolute text-right text-black text-xl font-bold font-['Calibri']">From £985</div>
                <div className="left-[58px] top-[235px] absolute text-black text-[15px] font-bold font-['Calibri']">A Simple Grids Package</div>
                <div className="w-[209px] h-52 left-[200px] top-0 absolute bg-white bg-opacity-80 rounded-tr-[5px] blur-sm" />
                <div className="w-[181px] h-[145px] left-[217px] top-[17px] absolute">
                    <div className="left-0 top-0 absolute text-black text-xl font-bold font-['Calibri']">Includes:</div>
                    <div className="left-0 top-[34px] absolute text-black text-xl font-normal font-['Calibri']">Software Assessments</div>
                    <div className="left-0 top-[63px] absolute text-black text-xl font-normal font-['Calibri']">Physical Tests</div>
                    <div className="left-0 top-[92px] absolute text-black text-xl font-normal font-['Calibri']">ROI & Plan</div>
                    <div className="left-0 top-[121px] absolute text-black text-xl font-normal font-['Calibri']">Quotes</div>
                </div>
            </div>
        </div>
        <div className="left-[27px] top-[34px] absolute text-black text-[40px] font-bold font-['Calibri']">All Packages</div>
    </div>
    <div className="w-[126px] h-10 left-[144px] top-[2952px] absolute text-black text-[25px] font-normal font-['Calibri']">Description</div>
    <div className="w-[1920px] h-20 left-0 top-0 absolute">
        <div className="w-[1920px] h-[42px] left-0 top-0 absolute bg-zinc-200" />
        <div className="w-[101px] h-8 left-[10px] top-[10px] absolute bg-white rounded-tl-lg rounded-tr-lg" />
        <div className="w-4 h-4 left-[18px] top-[17.50px] absolute">
            <div className="w-4 h-4 left-0 top-0 absolute bg-white rounded" />
            <div className="w-[13.37px] h-[13.40px] left-[1.31px] top-[1.31px] absolute">
                <div className="w-[0.64px] h-[0.64px] left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[0.98px] top-[0.98px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[1.96px] top-[1.96px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[12.73px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[10.78px] top-[1.96px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[1.96px] top-[10.78px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[10.78px] top-[10.78px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[11.76px] top-[11.76px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[0.98px] top-[11.76px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-[12.73px] top-[12.73px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                <div className="w-[0.64px] h-[0.64px] left-0 top-[12.76px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
            </div>
            <div className="w-[12.73px] h-[12.73px] left-[1.63px] top-[1.63px] absolute">
            </div>
            <div className="w-[12.73px] h-[12.73px] left-[1.63px] top-[1.63px] absolute">
                <div className="w-[12.73px] h-[12.73px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                <div className="w-[10.78px] h-[10.78px] left-[0.98px] top-[0.98px] absolute border border-zinc-500 border-opacity-20" />
                <div className="w-[8.82px] h-[8.82px] left-[1.96px] top-[1.96px] absolute border border-zinc-500 border-opacity-20" />
            </div>
            <div className="w-[13.06px] h-[13.08px] left-[1.47px] top-[1.47px] absolute">
                <div className="w-[0.33px] h-[0.33px] left-[12.73px] top-[12.73px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                <div className="w-[0.33px] h-[0.33px] left-0 top-[12.76px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
            </div>
            <div className="w-[9.16px] h-[7.47px] left-0 top-[5.22px] absolute">
                <div className="w-[7.32px] h-[7.47px] left-[0.91px] top-0 absolute bg-green-700 rounded-full border border-black" />
                <div className="w-[5.49px] h-[5.91px] left-[1.83px] top-[0.78px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
            </div>
            <div className="w-[9.41px] h-[9.47px] left-[6.40px] top-[3.37px] absolute">
                <div className="w-[12.32px] h-[0.62px] left-0 top-[9.03px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-[0.61px]" />
            </div>
        </div>
        <div className="left-[43px] top-[18px] absolute text-neutral-600 text-xs font-normal font-['Roboto'] tracking-tight">Home</div>
        <div className="w-[1920px] h-[38px] left-0 top-[42px] absolute bg-white shadow-inner" />
        <img className="w-[3px] h-3 left-[1896.67px] top-[55px] absolute" src="https://via.placeholder.com/3x12" />
        <img className="w-[22px] h-[22px] left-[1855px] top-[50px] absolute rounded-full" src="https://via.placeholder.com/22x22" />
        <div className="w-[1705px] h-7 left-[134px] top-[47px] absolute bg-gray-100 rounded-[14px]" />
        <img className="w-3 h-[11.47px] left-[1815px] top-[55px] absolute" src="https://via.placeholder.com/12x11" />
        <div className="left-[167px] top-[53px] absolute justify-start items-center inline-flex">
            <div className="text-neutral-800 text-sm font-normal font-['Roboto'] tracking-tight">simplegrids.com</div>
            <div className="text-neutral-500 text-sm font-normal font-['Roboto'] tracking-tight">/Home</div>
        </div>
        <img className="w-2 h-[10.50px] left-[147px] top-[55.50px] absolute" src="https://via.placeholder.com/8x10" />
        <img className="w-3 h-3 left-[107px] top-[55px] absolute" src="https://via.placeholder.com/12x12" />
    </div>
    <div className="w-[1920px] h-[118px] left-0 top-[77px] absolute">
        <div className="w-[1920px] h-[118px] left-0 top-0 absolute bg-white shadow" />
        <div className="w-[265px] h-[49px] left-[20px] top-[37px] absolute justify-center items-start gap-[7px] inline-flex">
            <div className="w-[49px] h-[49px] relative">
                <div className="w-[49px] h-[49px] left-0 top-0 absolute bg-white rounded-[13.52px]" />
                <div className="w-[40.95px] h-[41.02px] left-[4px] top-[4px] absolute">
                    <div className="w-0.5 h-0.5 left-0 top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[3px] top-[3px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[6px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[39px] top-0 absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[33px] top-[6px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[6px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[33px] top-[33px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[36px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[3px] top-[36px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-[39px] top-[39px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                    <div className="w-0.5 h-0.5 left-0 top-[39.07px] absolute bg-stone-500 bg-opacity-20 rounded-full" />
                </div>
                <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                </div>
                <div className="w-[39px] h-[39px] left-[5px] top-[5px] absolute">
                    <div className="w-[39px] h-[39px] left-0 top-0 absolute border border-zinc-500 border-opacity-20" />
                    <div className="w-[33px] h-[33px] left-[3px] top-[3px] absolute border border-zinc-500 border-opacity-20" />
                    <div className="w-[27px] h-[27px] left-[6px] top-[6px] absolute border border-zinc-500 border-opacity-20" />
                </div>
                <div className="w-10 h-[40.07px] left-[4.50px] top-[4.50px] absolute">
                    <div className="w-px h-px left-[39px] top-[39px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                    <div className="w-px h-px left-0 top-[39.07px] absolute bg-neutral-400 bg-opacity-20 rounded-full" />
                </div>
                <div className="w-7 h-[22.88px] left-0 top-[16px] absolute">
                    <div className="w-[22.41px] h-[22.88px] left-[2.80px] top-0 absolute bg-green-700 rounded-full border border-black" />
                    <div className="w-[16.81px] h-[18.11px] left-[5.60px] top-[2.38px] absolute bg-gradient-to-b from-zinc-300 to-black rounded-full border border-black" />
                </div>
                <div className="w-[28.82px] h-[28.99px] left-[19.60px] top-[10.32px] absolute">
                    <div className="w-[37.74px] h-[1.88px] left-0 top-[27.65px] absolute origin-top-left rotate-[-45.59deg] bg-gradient-to-b from-black via-white to-black rounded-sm" />
                </div>
            </div>
            <div className="w-[209px] h-[49px] relative">
                <div className="left-0 top-0 absolute text-sky-600 text-[40px] font-bold font-['Calibri']">Simple Grids</div>
                <div className="w-2 h-2 left-[20px] top-[6px] absolute bg-sky-600 rounded-full" />
                <div className="w-1 h-[0px] left-[23.50px] top-[8px] absolute origin-top-left rotate-90 border border-white"></div>
                <div className="w-1 h-[0px] left-[26px] top-[9.50px] absolute origin-top-left -rotate-180 border border-white"></div>
                <div className="w-2 h-2 left-[162.50px] top-[6px] absolute bg-sky-600 rounded-full" />
                <div className="w-1 h-[0px] left-[166px] top-[8px] absolute origin-top-left rotate-90 border border-white"></div>
                <div className="w-1 h-[0px] left-[168.50px] top-[9.50px] absolute origin-top-left -rotate-180 border border-white"></div>
            </div>
        </div>
        <div className="w-[427px] h-6 left-[1443px] top-[50px] absolute justify-end items-start gap-[60px] inline-flex">
            <div className="text-black text-xl font-bold font-['Calibri']">FAQs</div>
            <div className="text-black text-xl font-bold font-['Calibri']">Sign in</div>
            <div className="text-black text-xl font-bold font-['Calibri']">Join as a Service Provider</div>
        </div>
    </div>
    <div className="w-[1920px] h-[66px] left-0 top-[4328px] absolute">
        <div className="w-[1920px] h-[66px] left-0 top-0 absolute bg-white shadow" />
        <div className="left-[789.50px] top-[21px] absolute justify-start items-start gap-12 inline-flex">
            <div className="text-black text-xl font-bold font-['Calibri']">Simple Grids 2023</div>
            <div className="text-black text-xl font-bold font-['Calibri']">Privacy & Legal</div>
            <div className="text-black text-xl font-bold font-['Calibri']">Internal</div>
            <div className="text-black text-xl font-bold font-['Calibri']">Careers</div>
        </div>
    </div>
</div>