<div style={{width: '100%', height: '100%', position: 'relative', background: 'white'}}>
    <div style={{width: 1920, height: 198, left: 0, top: 830, position: 'absolute', background: 'white'}} />
    <div style={{width: 33, height: 21, left: 1868, top: 132, position: 'absolute'}}>
        <div style={{width: 32.42, height: 0, left: 0, top: 4, position: 'absolute', border: '3.06px black solid'}}></div>
        <div style={{width: 32.42, height: 0, left: 0, top: 12.25, position: 'absolute', border: '3.06px black solid'}}></div>
        <div style={{width: 32.42, height: 0, left: 0, top: 20.50, position: 'absolute', border: '3.06px black solid'}}></div>
    </div>
    <div style={{width: 721, left: 522, top: 4346.24, position: 'absolute'}}>
        <div style={{width: 82, height: 19.79, left: 639, top: 7.42, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Employee</div>
        <div style={{width: 150, height: 34.98, left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Simple Grids 2023</div>
        <div style={{width: 126, height: 34.98, left: 250, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Privacy & Legal</div>
        <div style={{width: 63, height: 34.98, left: 476, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Careers</div>
    </div>
    <div style={{width: 1838.05, height: 209, left: 32, top: 3546, position: 'absolute'}}>
        <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 60, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Trusted by</div>
        <div style={{width: 1764.05, height: 100, left: 74, top: 109, position: 'absolute', justifyContent: 'flex-start', alignItems: 'flex-start', gap: 24, display: 'inline-flex'}}>
            <img style={{width: 208.96, height: 100}} src="https://via.placeholder.com/209x100" />
            <img style={{width: 78.62, height: 100}} src="https://via.placeholder.com/79x100" />
            <img style={{width: 470.89, height: 100}} src="https://via.placeholder.com/471x100" />
            <img style={{width: 351.17, height: 100}} src="https://via.placeholder.com/351x100" />
            <img style={{width: 236.57, height: 100}} src="https://via.placeholder.com/237x100" />
            <img style={{width: 297.85, height: 100}} src="https://via.placeholder.com/298x100" />
        </div>
    </div>
    <div style={{width: 1920, height: 404, left: 0, top: 3865, position: 'absolute'}}>
        <div style={{width: 1920, height: 404, left: 0, top: 0, position: 'absolute', background: 'white'}} />
        <div style={{width: 1740, height: 300, left: 72, top: 41, position: 'absolute'}}>
            <div style={{left: 0, top: 1, position: 'absolute', color: 'black', fontSize: 60, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Join as a Service Provider</div>
            <div style={{width: 1194, height: 251, left: 1, top: 49, position: 'absolute', color: 'black', fontSize: 25, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
            <img style={{width: 484, height: 235, left: 1256, top: 0, position: 'absolute'}} src="https://via.placeholder.com/484x235" />
        </div>
        <div style={{width: 319.95, height: 75.57, left: 1462, top: 304, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 269.65, top: 56.25, position: 'absolute', transform: 'rotate(-90deg)', transformOrigin: '0 0', border: '3.22px white solid'}}></div>
            <div style={{left: 25.37, top: 25, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Join as a service provider</div>
        </div>
    </div>
    <div style={{width: 1920, height: 810, left: 0, top: 1852, position: 'absolute'}}>
        <div style={{width: 1920, height: 810, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{width: 1920, height: 347, paddingTop: 46, paddingBottom: 43, paddingLeft: 22, left: 0, top: 50, position: 'absolute', justifyContent: 'flex-end', alignItems: 'flex-start', gap: 50, display: 'inline-flex'}}>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Assessment - Retrofit</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Assessment - EPC</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Thermal Imaging</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>EICR</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Solar Panel Cleaning</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
        </div>
        <div style={{width: 1920, height: 347, paddingTop: 46, paddingBottom: 43, paddingLeft: 22, left: 0, top: 350, position: 'absolute', justifyContent: 'flex-end', alignItems: 'flex-start', gap: 50, display: 'inline-flex'}}>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Heat Pump Quality Audit</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Retrofit Co-ordination</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Heat Pump Maintenance</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Heat Loss Survey</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
            <div style={{width: 409, height: 258, position: 'relative'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 18, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>EV charger installation</div>
                <div style={{left: 345, top: 220, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£240</div>
                <div style={{width: 110, height: 208, left: 299, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
            </div>
        </div>
        <div style={{left: 27, top: 34, position: 'absolute', color: 'black', fontSize: 40, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>All Services</div>
    </div>
    <div style={{width: 1920, height: 284, left: 0, top: 674, position: 'absolute'}}>
        <div style={{width: 1920, height: 284, left: 0, top: 0, position: 'absolute'}}>
            <div style={{width: 1920, height: 284, left: 0, top: 0, position: 'absolute', background: '#D9D9D9'}} />
            <div style={{left: 431, top: 52, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 60, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Find the perfect package or service for you </div>
        </div>
        <div style={{width: 139, height: 72, left: 91, top: 145, position: 'absolute'}}>
            <div style={{width: 139, height: 50, left: 0, top: 11, position: 'absolute', background: 'white', boxShadow: '0px 0px 6px 1px #009A17', borderRadius: 20}} />
            <div style={{left: 23, top: 21, position: 'absolute', color: 'black', fontSize: 25, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Postcode</div>
        </div>
        <div style={{width: 556, height: 45, left: 253, top: 158.50, position: 'absolute'}}>
            <div style={{width: 556, height: 45, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px 0px 6px 1px #009A17', borderRadius: 20}}></div>
            <div style={{width: 34.50, height: 16.50, left: 510, top: 15.50, position: 'absolute', border: '4px black solid'}}></div>
        </div>
        <div style={{width: 185, height: 47, left: 832, top: 157.50, position: 'absolute'}}>
            <div style={{width: 185, height: 47, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 132.42, top: 17, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 11, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Age</div>
        </div>
        <div style={{width: 320, height: 48, left: 1040, top: 157, position: 'absolute'}}>
            <div style={{width: 320, height: 48, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 252.42, top: 21.75, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 11, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Problems to address</div>
        </div>
        <div style={{width: 288, height: 92, left: 1383, top: 156, position: 'absolute'}}>
            <div style={{width: 288, height: 92, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 20}} />
            <div style={{width: 186, left: 27, top: 10, position: 'absolute', opacity: 0.30, color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Narrate the problem in your own words/ click to speak</div>
            <div style={{width: 40, height: 40, left: 228, top: 26, position: 'absolute', borderRadius: 10, overflow: 'hidden', border: '1px #009A17 solid'}}>
                <div style={{width: 29.17, height: 22.50, left: 5.42, top: 15, position: 'absolute', background: '#1C274C'}}></div>
                <div style={{width: 19.17, height: 24.17, left: 10.42, top: 3.33, position: 'absolute', opacity: 0.50, background: '#1C274C'}}></div>
                <div style={{width: 8.33, height: 2.50, left: 21.25, top: 16.67, position: 'absolute', background: '#1C274C'}}></div>
                <div style={{width: 8.33, height: 2.50, left: 21.25, top: 11.67, position: 'absolute', background: '#1C274C'}}></div>
                <div style={{width: 5.83, height: 2.50, left: 10.42, top: 11.67, position: 'absolute', background: '#1C274C'}}></div>
                <div style={{width: 5.83, height: 2.50, left: 10.42, top: 16.67, position: 'absolute', background: '#1C274C'}}></div>
            </div>
        </div>
        <div style={{width: 142, height: 47, left: 1694, top: 157.50, position: 'absolute'}}>
            <div style={{width: 142, height: 47, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 117, top: 37.73, position: 'absolute', transform: 'rotate(-90deg)', transformOrigin: '0 0', border: '3.22px white solid'}}></div>
            <div style={{left: 14, top: 11, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>See Results</div>
        </div>
    </div>
    <div style={{width: 1920, height: 754.28, left: 0, top: 2679.72, position: 'absolute'}}>
        <div style={{width: 1920, height: 715, left: 0, top: 39.28, position: 'absolute', background: 'white', boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{width: 319.95, height: 75.57, left: 1139.84, top: 150.28, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 252.42, top: 35.75, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 29.72, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Number of Bedrooms</div>
        </div>
        <div style={{width: 319.95, height: 75.57, left: 1462, top: 630.28, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 269.65, top: 52, position: 'absolute', transform: 'rotate(-90deg)', transformOrigin: '0 0', border: '3.22px white solid'}}></div>
            <div style={{left: 25.37, top: 25, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Request a quote</div>
        </div>
        <div style={{width: 320, height: 75.57, left: 799.89, top: 150.28, position: 'absolute'}}>
            <div style={{width: 320, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 320, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 115.02, left: 35.43, top: 29.72, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Property Type</div>
            <div style={{width: 27.74, height: 13.26, left: 252.46, top: 35.75, position: 'absolute', border: '3.22px white solid'}}></div>
        </div>
        <div style={{width: 319.95, height: 75.57, left: 459.95, top: 150.28, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 252.42, top: 35.75, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 29.72, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Solutions</div>
        </div>
        <div style={{width: 319.95, height: 75.57, left: 120, top: 150.28, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 252.42, top: 35.75, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 29.72, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Service Types</div>
        </div>
        <div style={{width: 319.95, height: 75.57, left: 1478, top: 150.28, position: 'absolute'}}>
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 319.95, height: 75.57, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 16.08}} />
            <div style={{width: 27.73, height: 13.26, left: 252.42, top: 35.75, position: 'absolute', border: '3.22px white solid'}}></div>
            <div style={{left: 35.37, top: 29.72, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Property Age</div>
        </div>
        <div style={{left: 1515.16, top: 0, position: 'absolute', color: 'white', fontSize: 20.10, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Max Number of rooms</div>
        <div style={{left: 27, top: 73.28, position: 'absolute', color: 'black', fontSize: 40, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Request a quote</div>
        <div style={{width: 1680, height: 329, left: 120, top: 259.28, position: 'absolute', background: 'white', borderRadius: 20, border: '1px #009A17 solid'}}></div>
        <div style={{width: 1621, height: 65, left: 144, top: 332.28, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Hi there, I am looking for an insulation upgrade along with a Heat pump installation to convert my old oil boiler on my period property located near Oxford. I would like to have someone check out my property </div>
    </div>
    <div style={{width: 1262.55, height: 434, left: 314, top: 214, position: 'absolute'}}>
        <div style={{width: 1262.55, height: 434, left: 0, top: 0, position: 'absolute', background: 'white'}} />
        <div style={{width: 1168.13, height: 416.34, left: 47.35, top: 13.81, position: 'absolute'}}>
            <div style={{width: 1167.85, height: 159.13, left: 0, top: 0, position: 'absolute'}}>
                <div style={{width: 215.68, height: 38.34, left: -0, top: 0.53, position: 'absolute', textAlign: 'center', color: 'black', fontSize: 39.45, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>How it works</div>
                <div style={{width: 757.53, left: 4.60, top: 40.77, position: 'absolute', color: 'black', fontSize: 16.44, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>We vet a variety of service providers, ensuring that they are all certified and qualified to perform each service they offer and meet all government standards and more. This gives you peace of mind, as you can now be sure that the data you’re receiving is from a trustworthy, professional source, with no pressure on you to make any further purchases. We also have Verified Partners who </div>
                <div style={{width: 387.31, height: 159.13, left: 780.54, top: 0, position: 'absolute', background: '#D9D9D9'}} />
            </div>
            <div style={{width: 1167.48, height: 251.29, left: 0.66, top: 165.05, position: 'absolute'}}>
                <div style={{left: 809.48, top: -0, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 39.45, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>What are the benefits</div>
                <div style={{width: 521.46, left: 432.68, top: 51.29, position: 'absolute'}}><span style="color: 'black', fontSize: 16.44, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'">Reduce your Energy Bills<br/>Reduce your Carbon Emission<br/>Increase your comfort<br/></span><span style="color: 'black', fontSize: 16.44, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'"><br/>Are rooms in your house too hot or cold?<br/>Are you experiencing draughty windows?<br/>Are you thinking of adding a heat pump?<br/>Are you looking for Solar Panel installation?<br/>Are you planning to sell your house soon and would like to increase it’s value?<br/>Are you buying an Electric Vehicle?</span></div>
                <div style={{width: 223.58, left: 940.33, top: 51.29, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 16.44, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Ordering a Whole House energy Health Check-up package from us will allow you to get all the information you need to make an informed decision about your property to combat these problems and more!</div>
                <div style={{width: 387.31, height: 231.47, left: 0, top: 13.15, position: 'absolute', background: '#D9D9D9'}} />
            </div>
        </div>
    </div>
    <div style={{width: 1920, height: 871, left: 0, top: 981, position: 'absolute'}}>
        <div style={{width: 1920, height: 871, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{width: 398, height: 94, left: 761, top: 733, position: 'absolute'}}>
            <div style={{width: 398, height: 94, left: 0, top: 0, position: 'absolute', background: '#009A17', borderRadius: 20}} />
            <div style={{width: 34.50, height: 16.50, left: 184, top: 58, position: 'absolute', border: '4px white solid'}}></div>
            <div style={{left: 114, top: 19, position: 'absolute', color: 'white', fontSize: 25, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>See more results </div>
        </div>
        <div style={{width: 1920, height: 347, left: 0, top: 50, position: 'absolute'}}>
            <div style={{width: 409, height: 258, left: 940, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Enhance</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £600</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 481, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Solar PV + Battery Charger</div>
                <div style={{left: 272, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}> From £28,000</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{left: 217, top: 17, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                <div style={{width: 141, height: 105, left: 217, top: 51, position: 'absolute', flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start', gap: 3, display: 'inline-flex'}}>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Solar PV - 4kW</div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Battery - 10KWH </div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>DNO applications</div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Bird proofing</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1399, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1488</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1869, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 340, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£1488</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 22, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Base</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £450</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 166, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{width: 181, height: 132, left: 0, top: 34, position: 'absolute', flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start', gap: 3, display: 'inline-flex'}}>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Return on Investment</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Implementation Plan</div>
                    </div>
                </div>
            </div>
        </div>
        <div style={{width: 1920, height: 347, left: 0, top: 359, position: 'absolute'}}>
            <div style={{width: 409, height: 258, left: 940, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Champion</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1275</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 481, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Solar PV</div>
                <div style={{left: 277, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £20,000</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1399, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1488</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1869, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 340, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£1488</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 22, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Green</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £985</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
        </div>
        <div style={{left: 27, top: 34, position: 'absolute', color: 'black', fontSize: 40, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>All Packages</div>
    </div>
    <div style={{width: 1920, height: 871, left: 0, top: 981, position: 'absolute'}}>
        <div style={{width: 1920, height: 871, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{width: 1920, height: 347, left: 0, top: 50, position: 'absolute'}}>
            <div style={{width: 409, height: 258, left: 940, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Enhance</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £600</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 481, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Solar PV + Battery Charger</div>
                <div style={{left: 272, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}> From £28,000</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{left: 217, top: 17, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                <div style={{width: 141, height: 105, left: 217, top: 51, position: 'absolute', flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start', gap: 3, display: 'inline-flex'}}>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Solar PV - 4kW</div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Battery - 10KWH </div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>DNO applications</div>
                    <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Bird proofing</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1399, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1488</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1869, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 340, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£1488</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 22, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Base</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £450</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 166, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{width: 181, height: 132, left: 0, top: 34, position: 'absolute', flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start', gap: 3, display: 'inline-flex'}}>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Return on Investment</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                        <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Implementation Plan</div>
                    </div>
                </div>
            </div>
        </div>
        <div style={{width: 1920, height: 347, left: 0, top: 359, position: 'absolute'}}>
            <div style={{width: 409, height: 258, left: 940, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Champion</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1275</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 481, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Solar PV</div>
                <div style={{left: 277, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £20,000</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1399, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{left: 8, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 292, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £1488</div>
                <div style={{left: 8, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Installation Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 1869, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>[Name of Package]</div>
                <div style={{left: 340, top: 220, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>£1488</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
            <div style={{width: 409, height: 258, left: 22, top: 45, position: 'absolute'}}>
                <img style={{width: 409, height: 258, left: 0, top: 0, position: 'absolute', borderRadius: 5, border: '1px black solid'}} src="https://via.placeholder.com/409x258" />
                <div style={{width: 409, height: 51, left: 0, top: 207, position: 'absolute', background: 'white', borderTopLeftRadius: 5, borderTopRightRadius: 5, border: '1px black solid'}} />
                <div style={{width: 49, height: 49, left: 4, top: 208, position: 'absolute'}}>
                    <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                    <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                        <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    </div>
                    <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                        <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                        <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    </div>
                    <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                        <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                        <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                        <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    </div>
                    <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                        <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                        <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                    </div>
                    <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                        <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                        <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                    </div>
                </div>
                <div style={{left: 58, top: 210, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Energy Green</div>
                <div style={{left: 302, top: 220, position: 'absolute', textAlign: 'right', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>From £985</div>
                <div style={{left: 58, top: 235, position: 'absolute', color: 'black', fontSize: 15, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>A Simple Grids Package</div>
                <div style={{width: 209, height: 208, left: 200, top: 0, position: 'absolute', background: 'rgba(255, 255, 255, 0.80)', boxShadow: '4px 4px 4px ', borderTopLeftRadius: 5, filter: 'blur(4px)'}} />
                <div style={{width: 181, height: 145, left: 217, top: 17, position: 'absolute'}}>
                    <div style={{left: 0, top: 0, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Includes:</div>
                    <div style={{left: 0, top: 34, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Software Assessments</div>
                    <div style={{left: 0, top: 63, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Physical Tests</div>
                    <div style={{left: 0, top: 92, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>ROI & Plan</div>
                    <div style={{left: 0, top: 121, position: 'absolute', color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Quotes</div>
                </div>
            </div>
        </div>
        <div style={{left: 27, top: 34, position: 'absolute', color: 'black', fontSize: 40, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>All Packages</div>
    </div>
    <div style={{width: 126, height: 40, left: 144, top: 2952, position: 'absolute', color: 'black', fontSize: 25, fontFamily: 'Calibri', fontWeight: '400', wordWrap: 'break-word'}}>Description</div>
    <div style={{width: 1920, height: 80, left: 0, top: 0, position: 'absolute'}}>
        <div style={{width: 1920, height: 42, left: 0, top: 0, position: 'absolute', background: '#DEE1E6'}} />
        <div style={{width: 6, height: 8, left: 4, top: 34, position: 'absolute', background: 'white'}}></div>
        <div style={{width: 101, height: 32, left: 10, top: 10, position: 'absolute', background: 'white', borderTopLeftRadius: 8, borderTopRightRadius: 8}} />
        <div style={{width: 16, height: 16, left: 18, top: 17.50, position: 'absolute'}}>
            <div style={{width: 16, height: 16, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 4.41}} />
            <div style={{width: 13.37, height: 13.40, left: 1.31, top: 1.31, position: 'absolute'}}>
                <div style={{width: 0.64, height: 0.64, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 0.98, top: 0.98, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 1.96, top: 1.96, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 12.73, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 11.76, top: 0.98, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                <div style={{width: 0.64, height: 0.64, left: 10.78, top: 1.96, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 1.96, top: 10.78, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 10.78, top: 10.78, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 11.76, top: 11.76, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 0.98, top: 11.76, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 12.73, top: 12.73, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.64, height: 0.64, left: 0, top: 12.76, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
            </div>
            <div style={{width: 12.73, height: 12.73, left: 1.63, top: 1.63, position: 'absolute'}}>
                <div style={{width: 2.77, height: 0, left: 10.78, top: 1.96, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.10px rgba(181, 98, 87, 0.20) solid'}}></div>
                <div style={{width: 2.77, height: 0, left: 0, top: 12.73, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.10px rgba(181, 98, 87, 0.20) solid'}}></div>
                <div style={{width: 2.77, height: 0, left: 12.73, top: 12.73, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.10px rgba(181, 98, 87, 0.20) solid'}}></div>
                <div style={{width: 2.77, height: 0, left: 1.96, top: 1.96, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.10px rgba(181, 98, 87, 0.20) solid'}}></div>
            </div>
            <div style={{width: 12.73, height: 12.73, left: 1.63, top: 1.63, position: 'absolute'}}>
                <div style={{width: 12.73, height: 12.73, left: 0, top: 0, position: 'absolute', border: '0.13px rgba(136, 139, 141, 0.20) solid'}} />
                <div style={{width: 10.78, height: 10.78, left: 0.98, top: 0.98, position: 'absolute', border: '0.13px rgba(136, 139, 141, 0.20) solid'}} />
                <div style={{width: 8.82, height: 8.82, left: 1.96, top: 1.96, position: 'absolute', border: '0.13px rgba(136, 139, 141, 0.20) solid'}} />
            </div>
            <div style={{width: 13.06, height: 13.08, left: 1.47, top: 1.47, position: 'absolute'}}>
                <div style={{width: 0.33, height: 0.33, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 0.96, top: 0.96, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 1.96, top: 1.96, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 12.73, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 11.76, top: 0.98, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 10.78, top: 1.96, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 1.96, top: 10.78, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 10.78, top: 10.78, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 11.76, top: 11.76, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 0.98, top: 11.76, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                <div style={{width: 0.33, height: 0.33, left: 12.73, top: 12.73, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                <div style={{width: 0.33, height: 0.33, left: 0, top: 12.76, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
            </div>
            <div style={{width: 9.16, height: 7.47, left: 0, top: 5.22, position: 'absolute'}}>
                <div style={{width: 7.32, height: 7.47, left: 0.91, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.02px black solid'}} />
                <div style={{width: 5.49, height: 5.91, left: 1.83, top: 0.78, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.02px black solid'}} />
            </div>
            <div style={{width: 9.41, height: 9.47, left: 6.40, top: 3.37, position: 'absolute'}}>
                <div style={{width: 12.32, height: 0.62, left: 0, top: 9.03, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 0.61}} />
                <div style={{width: 12.32, height: 0.33, left: 0.56, top: 8.80, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '0.38113656640052795px 0.38113656640052795px 0.38113656640052795px ', border: '0.15px white solid', filter: 'blur(0.38px)'}}></div>
            </div>
        </div>
        <div style={{left: 43, top: 18, position: 'absolute', color: '#494C4F', fontSize: 12, fontFamily: 'Roboto', fontWeight: '400', letterSpacing: 0.20, wordWrap: 'break-word'}}>Home</div>
        <div style={{width: 7.50, height: 7.50, left: 90.25, top: 21.25, position: 'absolute', background: '#3C4043'}}></div>
        <div style={{width: 6, height: 8, left: 117, top: 34, position: 'absolute', transform: 'rotate(180deg)', transformOrigin: '0 0', background: 'white'}}></div>
        <div style={{width: 13.33, height: 13.33, left: 128.33, top: 18.33, position: 'absolute', background: '#3C4043'}}></div>
        <div style={{width: 1920, height: 38, left: 0, top: 42, position: 'absolute', background: 'white', boxShadow: '0px -1px 0px #DADCE0 inset'}} />
        <img style={{width: 3, height: 12, left: 1896.67, top: 55, position: 'absolute'}} src="https://via.placeholder.com/3x12" />
        <img style={{width: 22, height: 22, left: 1855, top: 50, position: 'absolute', borderRadius: 9999}} src="https://via.placeholder.com/22x22" />
        <div style={{width: 1705, height: 28, left: 134, top: 47, position: 'absolute', background: '#F1F3F4', borderRadius: 14}} />
        <img style={{width: 12, height: 11.47, left: 1815, top: 55, position: 'absolute'}} src="https://via.placeholder.com/12x11" />
        <div style={{left: 167, top: 53, position: 'absolute', justifyContent: 'flex-start', alignItems: 'center', display: 'inline-flex'}}>
            <div style={{color: '#202124', fontSize: 14, fontFamily: 'Roboto', fontWeight: '400', letterSpacing: 0.25, wordWrap: 'break-word'}}>simplegrids.com</div>
            <div style={{color: '#696A6C', fontSize: 14, fontFamily: 'Roboto', fontWeight: '400', letterSpacing: 0.25, wordWrap: 'break-word'}}>/Home</div>
        </div>
        <img style={{width: 8, height: 10.50, left: 147, top: 55.50, position: 'absolute'}} src="https://via.placeholder.com/8x10" />
        <img style={{width: 12, height: 12, left: 107, top: 55, position: 'absolute'}} src="https://via.placeholder.com/12x12" />
        <div style={{width: 12, height: 12, left: 76, top: 55, position: 'absolute', background: '#5F6368'}}></div>
        <div style={{width: 12, height: 11.69, left: 45, top: 55, position: 'absolute', background: '#BABCBE'}}></div>
        <div style={{width: 12, height: 11.69, left: 14, top: 55, position: 'absolute', background: '#5F6368'}}></div>
    </div>
    <div style={{width: 1920, height: 118, left: 0, top: 77, position: 'absolute'}}>
        <div style={{width: 1920, height: 118, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{width: 265, height: 49, left: 20, top: 37, position: 'absolute', justifyContent: 'center', alignItems: 'flex-start', gap: 7, display: 'inline-flex'}}>
            <div style={{width: 49, height: 49, position: 'relative'}}>
                <div style={{width: 49, height: 49, left: 0, top: 0, position: 'absolute', background: 'white', borderRadius: 13.52}} />
                <div style={{width: 40.95, height: 41.02, left: 4, top: 4, position: 'absolute'}}>
                    <div style={{width: 1.95, height: 1.95, left: 0, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 3, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 6, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 39, top: 0, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 36, top: 3, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)'}}></div>
                    <div style={{width: 1.95, height: 1.95, left: 33, top: 6, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 6, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 33, top: 33, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 36, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 3, top: 36, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 39, top: 39, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1.95, height: 1.95, left: 0, top: 39.07, position: 'absolute', background: 'rgba(181, 98, 87, 0.20)', borderRadius: 9999}} />
                </div>
                <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                    <div style={{width: 8.49, height: 0, left: 33, top: 6, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    <div style={{width: 8.49, height: 0, left: 0, top: 39, position: 'absolute', transform: 'rotate(-45deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    <div style={{width: 8.49, height: 0, left: 39, top: 39, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                    <div style={{width: 8.49, height: 0, left: 6, top: 6, position: 'absolute', transform: 'rotate(-135deg)', transformOrigin: '0 0', background: 'rgba(181, 98, 87, 0.20)', border: '0.30px rgba(181, 98, 87, 0.20) solid'}}></div>
                </div>
                <div style={{width: 39, height: 39, left: 5, top: 5, position: 'absolute'}}>
                    <div style={{width: 39, height: 39, left: 0, top: 0, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    <div style={{width: 33, height: 33, left: 3, top: 3, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                    <div style={{width: 27, height: 27, left: 6, top: 6, position: 'absolute', border: '0.40px rgba(136, 139, 141, 0.20) solid'}} />
                </div>
                <div style={{width: 40, height: 40.07, left: 4.50, top: 4.50, position: 'absolute'}}>
                    <div style={{width: 1, height: 1, left: 0, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 2.93, top: 2.93, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 6, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 39, top: 0, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 36, top: 3, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 33, top: 6, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 6, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 33, top: 33, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 36, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 3, top: 36, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)'}}></div>
                    <div style={{width: 1, height: 1, left: 39, top: 39, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                    <div style={{width: 1, height: 1, left: 0, top: 39.07, position: 'absolute', background: 'rgba(161.50, 161.50, 161.50, 0.20)', borderRadius: 9999}} />
                </div>
                <div style={{width: 28.04, height: 22.88, left: 0, top: 16, position: 'absolute'}}>
                    <div style={{width: 22.41, height: 22.88, left: 2.80, top: 0, position: 'absolute', background: 'conic-gradient(from 270deg at 84.29% 84.29%, #009A17 1deg, white 1deg, #3FB350 60deg, #009A17 179deg, white 185deg, #3AB14C 234deg)', borderRadius: 9999, border: '0.05px black solid'}} />
                    <div style={{width: 16.81, height: 18.11, left: 5.60, top: 2.38, position: 'absolute', background: 'linear-gradient(180deg, #D9D9D9 0%, black 100%)', borderRadius: 9999, border: '0.05px black solid'}} />
                </div>
                <div style={{width: 28.82, height: 28.99, left: 19.60, top: 10.32, position: 'absolute'}}>
                    <div style={{width: 37.74, height: 1.88, left: 0, top: 27.65, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', background: 'linear-gradient(90deg, #FF0000 0%, #FF0000 23%, #009A17 27%, #009A17 48%, #F8C101 52%, #F8C101 73%, #187BCD 78%, #187BCD 100%), linear-gradient(180deg, rgba(0, 0, 0, 0.50) 0%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0) 100%)', borderRadius: 1.87}} />
                    <div style={{width: 37.74, height: 1, left: 1.71, top: 26.96, position: 'absolute', transform: 'rotate(-45.59deg)', transformOrigin: '0 0', boxShadow: '1.1672307252883911px 1.1672307252883911px 1.1672307252883911px ', border: '0.47px white solid', filter: 'blur(1.17px)'}}></div>
                </div>
            </div>
            <div style={{width: 209, height: 49, position: 'relative'}}>
                <div style={{left: 0, top: 0, position: 'absolute', color: '#187BCD', fontSize: 40, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Simple Grids</div>
                <div style={{width: 8, height: 8, left: 20, top: 6, position: 'absolute', background: '#187BCD', borderRadius: 9999}} />
                <div style={{width: 4, height: 0, left: 23.50, top: 8, position: 'absolute', transform: 'rotate(90deg)', transformOrigin: '0 0', border: '1px white solid'}}></div>
                <div style={{width: 4, height: 0, left: 26, top: 9.50, position: 'absolute', transform: 'rotate(-180deg)', transformOrigin: '0 0', border: '1px white solid'}}></div>
                <div style={{width: 8, height: 8, left: 162.50, top: 6, position: 'absolute', background: '#187BCD', borderRadius: 9999}} />
                <div style={{width: 4, height: 0, left: 166, top: 8, position: 'absolute', transform: 'rotate(90deg)', transformOrigin: '0 0', border: '1px white solid'}}></div>
                <div style={{width: 4, height: 0, left: 168.50, top: 9.50, position: 'absolute', transform: 'rotate(-180deg)', transformOrigin: '0 0', border: '1px white solid'}}></div>
            </div>
        </div>
        <div style={{width: 427, height: 24, left: 1443, top: 50, position: 'absolute', justifyContent: 'flex-end', alignItems: 'flex-start', gap: 60, display: 'inline-flex'}}>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>FAQs</div>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Sign in</div>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Join as a Service Provider</div>
        </div>
    </div>
    <div style={{width: 1920, height: 66, left: 0, top: 4328, position: 'absolute'}}>
        <div style={{width: 1920, height: 66, left: 0, top: 0, position: 'absolute', background: 'white', boxShadow: '0px -4px 4px rgba(0, 0, 0, 0.25)'}} />
        <div style={{left: 789.50, top: 21, position: 'absolute', justifyContent: 'flex-start', alignItems: 'flex-start', gap: 48, display: 'inline-flex'}}>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Simple Grids 2023</div>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Privacy & Legal</div>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Internal</div>
            <div style={{color: 'black', fontSize: 20, fontFamily: 'Calibri', fontWeight: '700', wordWrap: 'break-word'}}>Careers</div>
        </div>
    </div>
</div>